# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e02af735a391f45a0ce33f561656291a5982ecacf2ce2ea0819015f59ed1de0579df882282e450c59de54092249b5311a1a40faeacd26763a0b0f464c505d341

test:
  secret_key_base: 6286735b333e204fb0fe002231f9b568c11067ed1568ca9823ebe6f092a3ee7e5b1932da0eabd971fa4083e9486951911de1a85a18106f40a9297c5be7b0d893

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
